name: '🚓'

on: push

jobs:
  job:
    name: ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: true

    steps:

      - name: Git
        uses: actions/checkout@v3

      - name: Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'

      - name: Verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
