name: '🚓'

on: push

jobs:
  job:
    name: ${{ matrix.java }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [ 8, 11, 16 ]
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: true

    steps:

      - name: Git
        uses: actions/checkout@v2

      - name: Java
        uses: actions/setup-java@v2.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          check-latest: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: '${{ runner.os }}-gradle-${{ hashFiles(''**/*.gradle'') }}'
          restore-keys: '${{ runner.os }}-gradle'

      - name: Verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
